### ISSUE TITLE
boundingRect?

### ISSUE THREAD

**Issue by akinhwan** [IsraelZablianov/draggable-vue-directive#1]
Is this the correct way to use this? 

`data () {
    return {
        handleId:"handle-id",
        draggableValue: {
            bottom:713.234375,
            height:48.25,
            left:0,
            right:1920,
            top:664.984375,
            width:1920,
            x:0,
            y:664.984375
            }
    }
  },`

**Comment by akinhwan** [comment]
The documentation is unclear, I would be happy to add a pull request editing it with fuller examples once this issue is resolved

**Comment by IsraelZablianov** [comment]
Hi @akinhwan ,
The currect way is to use an object contaning a field called "boundingRect" and pass it as the directive value.

for example: 
``` js
  import { Draggable } from 'draggable-vue-directive'
  ...
  export default {
        directives: {
            Draggable,
        },
        data() {
            return {
                handleId: "handle-id",
                draggableValue: { 
                    boundingRect: { 
                       bottom:713.234375, 
                       height:48.25, 
                       left:0, 
                       right:1920, 
                       top:664.984375, 
                       width:1920
                    }
                };
            }
        },
        mounted() {
            this.draggableValue.handle = this.$refs[this.handleId];
            this.draggableValue.onPositionChange = this.onPosChanged;
        },
        methods: {
            onPosChanged: function(pos) {
                console.log("left corner", pos.x);
                console.log("top corner", pos.y);
            }
        }
  ...
```
Let me know if I can close this issue.

Pull requests are always welcomed

**Comment by akinhwan** [comment]
Yes thank you for your response, you can close this issue. I think the documentation assumed I knew to include a bounding Rect object within the Draggable Value Object. I appreciate your help!
