### ISSUE TITLE
draggble not working with modals

### ISSUE THREAD

**Issue by ashutosh1807** [IsraelZablianov/draggable-vue-directive#10]
my draggable component has a modal attached to it which is triggered when the button is pressed that is present in the component itself....the component is indeed draggable but my screen becomes unresponsive when I open a modal
![screenshot 2](https://user-images.githubusercontent.com/34888417/41997571-f8c7679e-7a75-11e8-8fe9-a0c1ed1dc309.png)

**Comment by IsraelZablianov** [comment]
Hi,
I think you have a CSS problem.
Please try to change the 'z-index' or the 'position' of the modal.

Anyway, a good practice will be to remove the modal from the draggable component and put it along side with it.
