### ISSUE TITLE
Can I use clone helper as drag n drop?

### ISSUE THREAD

**Issue by ashutosh1807** [IsraelZablianov/draggable-vue-directive#12]

**Comment by IsraelZablianov** [comment]
Please provide explanation, example and screenshot

**Comment by ashutosh1807** [comment]
See I have a button now as I click it and drag into my dropping area I want a dynamic component to be added at mouse drop position...how can I do this can you give a sample code?or should I give a sample code

**Comment by IsraelZablianov** [comment]
You can use the 'onPositionChange' event to get the mouse drop position, and rest is up to you..
