### ISSUE TITLE
I can't select the content of the element dragged

### ISSUE THREAD

**Issue by wQueryLoveMm** [IsraelZablianov/draggable-vue-directive#13]
I can't select the content of the element dragged

The issue is that , when I dragging the element , I want to copy some words of the element, but the fact is that the whole element is dragging , so, how can I copy the content of the element.

**Comment by IsraelZablianov** [comment]
By default you can't.
But you can override the CSS property 'user-select' to 'text' or 'all' for example and use the handler to make the inner div or span not draggable.

Let me know if further help is needed.

**Comment by cmcleese** [comment]
How is possible to highlight text that is inside a draggable container?
I've set the handle to be something other than the text but all mouse events a prevented from bubbling down.
I believe you should do a check on the handle if its matches and only then cancel the events.
That way children elements can still have their native or custom events intact.
Ex:
* text highlight
* interactive chart

I would like to recommended reopening this issue for consideration.
