### ISSUE TITLE
Prevent clink while dragging the element

### ISSUE THREAD

**Issue by gokatz** [IsraelZablianov/draggable-vue-directive#14]
Hi. Thanks for this plugin. It speeds up my prototyping. 🙂 

One enhancement that I could see is that preventing the click event while dragging the element. I bind a click event for my element which is draggable. When I release the cursor after dragging, the click event gets triggered. Is there any way I can suppress this click event on drag release?

**Comment by IsraelZablianov** [comment]
Hi thanks for your support,
You can use onPosChanged method of draggable value and stopPropogation using the third variable
something like:
onPosChanged(positionDiff, absolutePosition, event) {
     event.stoppropagation();
}

**Comment by gokatz** [comment]
Thanks for this @IsraelZablianov. But I can still reproduce the scenario even after specifying `onPositionChange`. Please refer https://codesandbox.io/s/x9n5p4xrzp
