### ISSUE TITLE
should reset `right` of target element when dragging

### ISSUE THREAD

**Issue by e-cloud** [IsraelZablianov/draggable-vue-directive#17]
there will be cases that you drag an already positioned element with `right` assigned. Without resetting `right`, it will cause a resizing-like behavior, which is not desired.

**Comment by IsraelZablianov** [comment]
In that case it should be done outside of the directive to enable diversity of options.
For example what if I want my element to be dragged with a certain margin?

The developer should decide and reset whatever he wants.
