### ISSUE TITLE
Issue on latest version chrome, chrome 69.xx

### ISSUE THREAD

**Issue by luoye-fe** [IsraelZablianov/draggable-vue-directive#18]
The screenshot below, and the dom in red box is same one.

![](https://s10.mogucdn.com/mlcdn/c45406/180911_8gjh39ii5k2e79k9ghi5fi821bgi2_1642x587.png)

**Comment by IsraelZablianov** [comment]
Sorry I didn't understand your problem
Can you explain?

**Comment by euskalhenriko** [comment]
Same problem in chrome Version 69 on Windows 10. It work on the same version of Chrome in Linux and still work on chrome Canary Version 71 on Windows 10.
To reproduce it:
- Mouse press on draggable element and start drag: mouse pointer is not-allowed, element doesn't move and movement is like when you drag an image on chrome (sort of shadow). onDragStart and onPosChanged are fired, but onPosChanged is fired between 2 to 5 times only (I think is time based)
- End drag (release mouse left button): mouse pointer is move and element move with the mouse movements. No onDragEnd event fired and onPosChanged start working well
- Another click: element is released. onDragStart and onDragEnd is fired
If another click is doing when moving, element go near to previous positions

**Comment by IsraelZablianov** [comment]
Done
