### ISSUE TITLE
form input tag does not work inside draggable

### ISSUE THREAD

**Issue by MichaelNgugiN** [IsraelZablianov/draggable-vue-directive#25]
Hi,
Trying to enter text inside form input, don't know why i cant seem to focus on the input.

**Comment by IsraelZablianov** [comment]
I will check it out as soon as I can

**Comment by IsraelZablianov** [comment]
Hi @MichaelNgugiN 
Fixed in v2.0.5
Please let me know if you still have any problem.

Israel
