### ISSUE TITLE
draggable-vue-directive doesn't support touch ?

### ISSUE THREAD

**Issue by Alakeel** [IsraelZablianov/draggable-vue-directive#26]
Why the library doesn't support touch? Just tried the demo using a touch screen and I can't drag and drop using touch.

**Comment by Alakeel** [comment]
Can I create a pull request to update this library to support touch events ?

**Comment by IsraelZablianov** [comment]
You are right, will be done hopefully in the next version

**Comment by hvp130230** [comment]
Any plans to include this?

**Comment by IsraelZablianov** [comment]
Yes

**Comment by IsraelZablianov** [comment]
Added touch support
