### ISSUE TITLE
directive not working if draggable="true"

### ISSUE THREAD

**Issue by devrobinkroeker** [IsraelZablianov/draggable-vue-directive#29]
Is there a way to set draggable="true" and to use the v-draggable directive at the same time?

**Comment by IsraelZablianov** [comment]
Currently the directive uses the attribute `draggable` and sets it to true.
So you don't need to set it yourself.

**Comment by devrobinkroeker** [comment]
I want to react to the @dragend event because with that event I can pass specific data. The problem is only with the v-draggable directive I'am not able to pass the data.
I want to make something like this: @dragend="drag-end(node.name)"

**Comment by IsraelZablianov** [comment]
if you will inspect the element that the `v-draggable` directive is on, you will see that the `draggable` attribute is already there.
So the dragend event should work for you.
If it doesn't please share a code so I could better help.

**Comment by devrobinkroeker** [comment]
`<li v-for="node in filtered_nodes" :key="node.id">
                <div v-draggable="draggableValue" :id="node.name" :style="style(node.background_color, node.x, node.y)" class="node">
                    <label class="text">
                        {{ node.name }}
                    </label>
                </div>
            </li>`

I need every node.name in the for loop but the dragend event in the v-draggable directive isn't in the loop

**Comment by IsraelZablianov** [comment]
`draggableValue` can take an event of `[onDragEnd](https://github.com/IsraelZablianov/draggable-vue-directive#ondragend)` I suggest that you will make a draggableValue for each node with a different `onDragEnd` event.

something like: 

```js
    const filtered_nodes = [
        {
             node: node1 ,
             draggableValue: {
                  ...baseDraggableValue,
                  onDragEnd: () => {
                      console.log(node1.name);
                  }
             }    
        }
    ]

```

in the template: 

```html
<li v-for="filtered_node in filtered_nodes" :key="node.id"> <div v-draggable="filtered_node.draggableValue" :id="filtered_node.node.name" :style="style(filtered_node.node.background_color, filtered_node.node.x, node.y)" class="node"> <label class="text"> {{ filtered_node.node.name }} </label> </div> </li>
```

**Comment by devrobinkroeker** [comment]
Thank you. I will try
