### ISSUE TITLE
Is there a way to manage z-index with this?

### ISSUE THREAD

**Issue by RailRunner166** [IsraelZablianov/draggable-vue-directive#33]
I am using this to make draggable windows in a project. i need to bring a window to the front when it is being dragged, is there a way to do this with z-index?

**Comment by IsraelZablianov** [comment]
Yes,
You can use the [onpositionchange](https://github.com/IsraelZablianov/draggable-vue-directive#onpositionchange) event handler, e.g. 
```js
....
            onPosChanged: function(positionDiff, absolutePosition, event) {
                // el is the element that been dragged, you can find it using event.target or ref
                el.style.zIndex = "1";
            }

```
