### ISSUE TITLE
[question] Position: fixed

### ISSUE THREAD

**Issue by ehhc** [IsraelZablianov/draggable-vue-directive#36]
Hi,
is there a reason why you set the position attribute to `fixed` and not e.g. `relative`?

**Comment by IsraelZablianov** [comment]
Yes,
It helps for variety of calculation

**Comment by ehhc** [comment]
so it would be a bad idea to set it to `position: relative` at the moment?

**Comment by IsraelZablianov** [comment]
Some of the features might not work as expected

**Comment by ehhc** [comment]
okay. thanks for the reply :)
