### ISSUE TITLE
Using bottom, right for position and percent values

### ISSUE THREAD

**Issue by Excelsiorer** [IsraelZablianov/draggable-vue-directive#38]
Hello! 
How can i set initialPosition like 
<code>
initialPosition: {
                        "bottom": '10%',
                        "right": '10vw'
                    }
</code>

**Comment by IsraelZablianov** [comment]
you can't, it should be number only

**Comment by Excelsiorer** [comment]
It's so bad. I will try to make it and commit

**Comment by Excelsiorer** [comment]
It's so bad. I will try to make it and commit
