### ISSUE TITLE
Text selection with handler

### ISSUE THREAD

**Issue by salsa2k** [IsraelZablianov/draggable-vue-directive#40]
Hi,

I saw in your image demo in the very end that you are able to select the text using the handler.... 

https://camo.githubusercontent.com/9f55e388c704bff5bc49499edf06b156b160cbfc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f366e554f316c574d6b657948356e66572f67697068792e676966

How you do it? right now I'm trying but I can't select the text inside.

Thanks

**Comment by IsraelZablianov** [comment]
By default a draggable element text is not selectable (depends on the browser you are using).
Simply add `user-select: auto` to the css of the element

**Comment by IsraelZablianov** [comment]
If further help is needed please reopen the issue
