### ISSUE TITLE
draggable with handler doesn't work

### ISSUE THREAD

**Issue by Dontorpedo** [IsraelZablianov/draggable-vue-directive#41]
Hi,

I am using the code from the example (Draggable with handler) but it doesn't work..

the whole div is stil draggable.. the handler seems to be not recognized.

pls help :)

**Comment by IsraelZablianov** [comment]
Hi,
Can you share a link to your code?

**Comment by Dontorpedo** [comment]
`<table class="table  w-1/2  p-3"
                       v-bind:class="[{ 'stickyDiv card': isSticky }]" v-draggable="draggableValue">
                    <div class="handler" :ref="handleId" >
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M5 3h4a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm0 2v4h4V5H5zm10-2h4a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm0 2v4h4V5h-4zM5 13h4a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4c0-1.1.9-2 2-2zm0 2v4h4v-4H5zm10-2h4a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2v-4c0-1.1.9-2 2-2zm0 2v4h4v-4h-4z"/></svg>
                    </div>
                    <draggable :list="tour.invoice_position" :options="{animation:200, group: 'touren'}" :element="'tbody'" @change="update" >

                        <tr  v-if="pos.tour_id == '100' && pos.objekte.status == 'aktiv' && isVisible || pos.tour_id == '100' &&pos.objekte.status == 'WW' && isVisible " v-for="(pos, index) in tour.invoice_position" :key="pos.id" :data-id="pos.id">
                            <td >{{pos.objekte.zipcode}}, {{pos.objekte.street}}               {{pos.objekte.additional_street}}</td>
                            <td>{{pos.pos_description}} {{pos.pos_id}}
                             </td>

                        </tr>
                    </draggable>

                </table>`


and the other part:

`<script>
    import draggable from 'vuedraggable'
    import { Draggable } from 'draggable-vue-directive'
    export default {
        components: {
            draggable
        },
		directives: {
            Draggable,
		},
        watch: {
            filtered() {
                console.log('Foo Changed!');
            }
        },
        data() {
            return {
                opened: [],
                touren: [],
                temp: [],
                search: '',
                isSticky: false,
				isVisible: false,
                handleId: "handle-id",
                draggableValue: { handle: undefined }

            }
        },
        mounted() {
            this.getTouren();
            this.draggableValue.handle = this.$refs[this.handleId];
        },

......... ......... .........
`

**Comment by IsraelZablianov** [comment]
Actually in your example you are not using the directive at all...
In the example that you provided you are using a different library.
For example how to use the draggable-vue-directive please look at [this](https://github.com/IsraelZablianov/draggable-demo) repo

**Comment by IsraelZablianov** [comment]
```vue
<template>
            <div class="draggable-with-handler" v-draggable="draggableWithHandler">
                Use Handler To Drag Me
                <div class="handler" ref="handler">
                    I am Handler
                </div>
            </div>
    </div>
</template>

<script lang="ts">
import { Vue, Component, Prop } from "vue-property-decorator";
import { Draggable, DraggableValue } from "draggable-vue-directive";
@Component({
    directives: {
        Draggable
    }
})
export default class App extends Vue { 
    draggableWithHandler: DraggableValue = { handle: undefined };

    mounted() {
  
        this.draggableWithHandler.handle = this.$refs.handler as HTMLElement;
    }


}
</script>
```

this is one of the examples from this repo.
