### ISSUE TITLE
How can I select the text outside the handle like your demo

### ISSUE THREAD

**Issue by knight96** [IsraelZablianov/draggable-vue-directive#42]

**Comment by knight96** [comment]
I set my handle as the border of my element,but when I drag the content inside,it shows an effect of no-dragging.

**Comment by IsraelZablianov** [comment]
Please look at this issue: https://github.com/IsraelZablianov/draggable-vue-directive/issues/40

Is it what you asking for?

**Comment by knight96** [comment]
thanks  : )
