### ISSUE TITLE
Prevent element from being dragged out of current viewport

### ISSUE THREAD

**Issue by quantrung9** [IsraelZablianov/draggable-vue-directive#44]
The feature dragging within the bounds of a parent element is excellent. But I wonder is there any way to upgrade it so that it can prevent the element from dragging outside the viewport? Thanks in advance.

For now, I'm using getboundingClientRect to detect and then set the initial position.

![2020-05-23_19-14](https://user-images.githubusercontent.com/8580008/82730412-9b1fe480-9d29-11ea-92ef-84c6b2811db0.png)

**Comment by IsraelZablianov** [comment]
Hi Quan,
you can achieve this functionality using [boundingRect](https://github.com/IsraelZablianov/draggable-vue-directive#boundingrect) feature.
get the viewport bounding rectangle and simply pass it to the draggable directive value as described.

You can calculate the viewport boundaries yourself or get the html element client rect.
A simple example would be:

```js
const boundingRect = document.documentElement.getBoundingClientRect();
// pass the boundingRect variable to the boundingRect property of draggable value
```

another way will be to pass the `document.documentElement' as the [bounding element](https://github.com/IsraelZablianov/draggable-vue-directive/#boundingelement).

**Comment by quantrung9** [comment]
Thanks @IsraelZablianov, I did it :D
