### ISSUE TITLE
Doesn't seem to set initial pos correctly

### ISSUE THREAD

**Issue by grofit** [IsraelZablianov/draggable-vue-directive#7]
I have a scenario where I have a few tabs and each will show different things to drag, and each one of those objects has a position property which is updated (and synced back up to main object) when the position changed event is raised. This information is pumped out to the console so I can see the x/y is correct and being updated.

Now the problem occurs when I swap tabs (i.e current elements vanish and new are put on) and I return to the previous tab where I moved things around, they are just shown at 0,0 even though they have a position property with values different to 0,0, this is with `initialPosition` being set too.

So just to be clear code looks like:

```ts
 public draggableOptions = {
	handle: this.$refs.headerElement,
	onPositionChange: this.updatePosition,
	initialPosition: this.node.position
};

public updatePosition(newPosition) {
	this.$emit("update:position", newPosition); // parent assigns this to this.node.position
}
```

Then when I go to drag the elements shown at 0,0 they they pop back to where they were, so it looks like its a case of when the elements come back on the position is only updated when I start to drag, but I was expecting that the position would just automatically be set when the directive is applied.

Anyway feel free to say this is as per designed and I need to seed the position manually myself, but I just wanted to raise it.

**Comment by IsraelZablianov** [comment]
If I understand you currecetly, I think that all you need to do is to toggle resetInitialPos,
As written in the readme about initialPosition:

'Sets the absolute starting position of this element.
**Will be applied when resetInitialPos is true**.'

Please let me know if further help is needed

**Comment by grofit** [comment]
If I do that it enters into an infinite loop and locks up the browser, I assumed it was down to me updating the position on the object with the on move and setting the last known position to the initial post etc.

**Comment by IsraelZablianov** [comment]
Do you have a public repository with your code to share?

**Comment by grofit** [comment]
sorry not at the moment, when I am back in the office next week I will see if I can reproduce on codepen or something.
